### PR TITLE
1.18.2 Fixes

### LINKED ISSUE #1086: Symmetry wand placing double slabs
### Describe the Bug

When you place a slab with the symmetry wand active, the copies it creates instntly transform into a double slab as if u placed it twice. (Only happens in Fabric create)

### Reproduction Steps

1.Place symmetry wand
2.Place a slab

### Expected Result

Two half slabs instead a half slab and a full block of slabs

### Crash Report or Log

_No response_

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

create-fabric-0.5.1-c-build.1160+mc1.19.2

### Additional Context

First I thought it was an incompatibility with any other mod from my modpack, but then I tried with just the cerate mod and the bug was still there.

### LINKED ISSUE #1139: Server crashes when placing deployer between mismatched RPMs with Jade installed
### Describe the Bug

When Jade is installed, placing a deployer between two cogs rotating at different speeds causes the game/server to crash. The issue does not occur without Jade.

### Reproduction Steps

1. Set up two inline cogs rotating at different speeds.
2. Place a deployer between them, connected to both cogs.

### Expected Result

The game should not crash.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/37044997/fde3173a-3114-4f03-adce-61af5807b7af

### Crash Report or Log

https://mclo.gs/HSCSXkG

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Fabric Loader: `0.14.23`
Fabric API: `0.76.1+1.19.2`
Jade: `8.7.3`

### Additional Context

Full log: https://mclo.gs/f4YGrir

### LINKED ISSUE #1316: [Patch F] Train Observer Crash
### Describe the Bug

Hi, I'm running the latest commit fb322c86b2f4074b241a0b5079f667ee7368ceec and I imported a singleplayer world from 0.5.1d to see if any crashes or issues occur. Noticed that when train observer saves it's NBT a crash occurs.

### Reproduction Steps

1. Place down train observer linked to track in singleplayer
2. Try to go to main menu to force world save.
3. Crash

### Expected Result

No crash

### Screenshots and Videos

_No response_

### Crash Report or Log

https://mclo.gs/qjjG4z9

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

It's the dev environment, so whatever was in that commit.

### Additional Context

_No response_

### LINKED ISSUE #1317: [Patch F] getVersion() may not be called during transaction causing crash.
### Describe the Bug

Hi, I'm running commit https://github.com/Fabricators-of-Create/Create/commit/fb322c86b2f4074b241a0b5079f667ee7368ceec and I imported a singleplayer world from 0.5.1d to see if any crashes or issues occur. It seems that some optimisations made in Patch E on Forge (0510ea3e20f0bfadf5df6100fddf57584d691ffe) when ported to Fabric cause a crash under certain circumstances. 

Note: I built the project and ran it in an instance with just sodium, indium and spark (versions down below) so I could measure the performance to make sure the optimisations work as this was causing issues in my world.

Thanks for the work you put into this great mod.

### Reproduction Steps

1. Place down single item vault block
2. Fill item vault
3. Try to put another stack into item vault via chute or funnel
4. Crash

### Expected Result

No crash and for the optimisations made on Forge to still work on Fabric.

### Screenshots and Videos

_No response_

### Crash Report or Log

https://mclo.gs/nvCl8Uw

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.18.2

### Other Mods

Tried to match dev environment as closely as possible.
Fabric API 0.77.0
indium 1.0.7
Sodium 1.18.2-0.4.1
Spark 1.10.39

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by IThundxr**
- Fix #1316
- Fix #1317
- Fix #1139
- Fix #1086

### CODE REVIEW

File: src/main/java/com/simibubi/create/content/logistics/chute/ChuteBlockEntity.java [hunk 1]
```diff
@@ -389,10 +389,11 @@ private boolean handleDownwardOutput(boolean simulate) {
 				}
 				if (inserted != 0)
 					return true;
-				invVersionTracker.awaitNewVersion(inv);
 				if (direction == Direction.DOWN)
 					return false;
 			}
+
+			invVersionTracker.awaitNewVersion(inv);
```
Comment (TropheusJ) [inline src/main/java/com/simibubi/create/content/logistics/chute/ChuteBlockEntity.java:396]: this is an incorrect change in behavior

Comment (IThundxr) [reply src/main/java/com/simibubi/create/content/logistics/chute/ChuteBlockEntity.java:396]: awaitNewVersion can't be called during a transaction so I'm not sure where it should really be called from

Comment (TropheusJ) [reply src/main/java/com/simibubi/create/content/logistics/chute/ChuteBlockEntity.java:396]: move the early return too. leave a comment saying why it's outside it
